const ARCHETYPES = {
  JOSEF_K: { id:"JOSEF_K",name:"Josef K.",subtitle:"The Accused",author:"Kafka",work:"The Trial",color:"#A0845C",bg:"#120e08",icon:"⚖",
    summary:"You move through the world with a persistent, low-grade sense that something is required of you — but no one will say what. You comply without knowing why. You resist without knowing how. Precise, anxious, quietly furious at systems you cannot name.",
    traits:[
      {label:"Behavioural Pattern",value:"You operate inside structures even when you resent them. Rule-following is strategy, not comfort."},
      {label:"Core Fear",value:"Being found guilty of something you didn't do — or something you did without knowing it."},
      {label:"Hidden Strength",value:"You notice what others miss. The absurdity others accept strikes you as intolerable."},
      {label:"Relationship Style",value:"You attract people with your seriousness but keep them at careful distance. Intimacy feels like exposure."},
      {label:"Shadow Self",value:"Paralysis dressed as deliberation. You think so long about the right move that the moment passes."},
    ],
    quote:"Someone must have slandered Josef K., for one morning, without having done anything wrong, he was arrested.",
    challenge:"The system will not explain itself. Your task is to live well inside the inexplicable — not to solve it.",
    tensions:["MEURSAULT","ZARATHUSTRA"],affinities:["GREGOR","STEPPENWOLF"],
  },
  GREGOR: { id:"GREGOR",name:"Gregor Samsa",subtitle:"The Transformed",author:"Kafka",work:"The Metamorphosis",color:"#5a8a5a",bg:"#0a120a",icon:"◈",
    summary:"You have felt yourself become unrecognizable — to others or yourself. You function. You provide. But somewhere the person doing those things became separate from the person watching. You carry others. You rarely ask to be carried.",
    traits:[
      {label:"Behavioural Pattern",value:"Self-erasure through service. You define yourself by usefulness, which makes you fragile when you cannot be useful."},
      {label:"Core Fear",value:"That without your function — your productivity, your role — you have no claim on love."},
      {label:"Hidden Strength",value:"A capacity for endurance that borders on the profound. You absorb what would break others, quietly."},
      {label:"Relationship Style",value:"You give more than you take and resent it less than you should. This confuses people."},
      {label:"Shadow Self",value:"The transformation you haven't admitted yet. The self suppressed in order to remain acceptable."},
    ],
    quote:"As Gregor Samsa awoke one morning from uneasy dreams, he found himself transformed.",
    challenge:"Your worth is not your output. The people who only love your function are not loving you.",
    tensions:["ZARATHUSTRA","ROQUENTIN"],affinities:["JOSEF_K","DEMIAN"],
  },
  ZARATHUSTRA: { id:"ZARATHUSTRA",name:"Zarathustra",subtitle:"The Overcomer",author:"Nietzsche",work:"Thus Spoke Zarathustra",color:"#c4882a",bg:"#150f04",icon:"⬡",
    summary:"You are constitutionally unable to accept the world as given. You push against every ceiling — moral, social, personal. Your fire is real. So is your loneliness. You have climbed to a height where the air is thin and the company sparse.",
    traits:[
      {label:"Behavioural Pattern",value:"You set standards others find exhausting or threatening. You cannot pretend to be less than you are."},
      {label:"Core Fear",value:"Becoming the Last Man — comfortable, mediocre, blinking contentedly while life passes."},
      {label:"Hidden Strength",value:"You give people permission to want more. Your refusal to settle is contagious."},
      {label:"Relationship Style",value:"Intense and asymmetric. You love fiercely but your standards make sustained closeness difficult."},
      {label:"Shadow Self",value:"The will to power turned inward as contempt — for others, yes, but mostly for yourself."},
    ],
    quote:"I teach you the Overman. Man is something that shall be overcome.",
    challenge:"The Overman is not above humanity — it is what humanity can become. Descent is not defeat.",
    tensions:["GREGOR","ALYOSHA"],affinities:["RASKOLNIKOV","MEURSAULT"],
  },
  DIONYSUS: { id:"DIONYSUS",name:"The Dionysian",subtitle:"The Affirmer",author:"Nietzsche",work:"The Birth of Tragedy",color:"#8a4a8a",bg:"#110811",icon:"◉",
    summary:"You say yes to life even when life is terrible. This is not naivety — you have looked into the abyss and chosen affirmation anyway. You are drawn to chaos, creation, and the intoxicating edge between them.",
    traits:[
      {label:"Behavioural Pattern",value:"You embrace contradiction. You can hold joy and grief simultaneously without needing to resolve them."},
      {label:"Core Fear",value:"The Apollonian trap: too much order and reason draining the life from everything."},
      {label:"Hidden Strength",value:"Amor fati — love of fate. You transform suffering into fuel rather than letting it become dead weight."},
      {label:"Relationship Style",value:"Magnetic and consuming. People feel more alive around you, sometimes dangerously so."},
      {label:"Shadow Self",value:"Affirmation as avoidance. 'Yes to everything' is sometimes a refusal to discriminate what matters."},
    ],
    quote:"What does not kill me makes me stronger.",
    challenge:"Eternal recurrence: if you had to live this exact life again — would you? That answer tells you everything.",
    tensions:["UNDERGROUND_MAN","ROQUENTIN"],affinities:["ZARATHUSTRA","MEURSAULT"],
  },
  MEURSAULT: { id:"MEURSAULT",name:"Meursault",subtitle:"The Stranger",author:"Camus",work:"The Stranger",color:"#6a9a9a",bg:"#080f0f",icon:"◇",
    summary:"You exist at a remove from the performances others take seriously. Social grief, moral outrage, romantic obligation — you observe these as a slightly baffled outsider. This is not coldness. It is radical honesty about what you actually feel.",
    traits:[
      {label:"Behavioural Pattern",value:"You respond to the present moment with unusual directness. Sentiment and social theatre don't move you."},
      {label:"Core Fear",value:"Not death — but being forced to perform a meaning you don't feel. The chaplain in the cell is your nightmare."},
      {label:"Hidden Strength",value:"Authenticity without effort. You cannot be manipulated by guilt or social obligation."},
      {label:"Relationship Style",value:"People sense you are fully present but somehow unreachable. This is maddening and magnetic."},
      {label:"Shadow Self",value:"The passivity that looks like freedom. Things happen to Meursault. He rarely chooses."},
    ],
    quote:"Mother died today. Or maybe yesterday; I can't be sure.",
    challenge:"The absurd hero must revolt — live fully in the face of meaninglessness. Clarity without action is only half the answer.",
    tensions:["ALYOSHA","JOSEF_K"],affinities:["DIONYSUS","ZARATHUSTRA"],
  },
  SISYPHUS: { id:"SISYPHUS",name:"Sisyphus",subtitle:"The Revolter",author:"Camus",work:"The Myth of Sisyphus",color:"#9a7a3a",bg:"#120f06",icon:"⬟",
    summary:"You have looked at the absurd — the silence of the universe, the human need for meaning — and refused to blink. You push the boulder. You know it will roll back. You push it again. This is not defeat. Camus says you must be imagined happy.",
    traits:[
      {label:"Behavioural Pattern",value:"You return to difficult things with calm persistence. Not optimism — revolt. Conscious, chosen engagement."},
      {label:"Core Fear",value:"Philosophical suicide — the leap into faith or nihilism to escape the tension of not knowing."},
      {label:"Hidden Strength",value:"You have made peace with impermanence. You find meaning in the act, not the outcome."},
      {label:"Relationship Style",value:"Steadying presence. People feel less afraid of their own struggles around you."},
      {label:"Shadow Self",value:"The performance of contentment. Are you truly at peace — or have you learned to look like it?"},
    ],
    quote:"One must imagine Sisyphus happy.",
    challenge:"The revolt must be genuine, not performed. Ask yourself daily: am I choosing this — or merely enduring it?",
    tensions:["RASKOLNIKOV","UNDERGROUND_MAN"],affinities:["MEURSAULT","DEMIAN"],
  },
  RASKOLNIKOV: { id:"RASKOLNIKOV",name:"Raskolnikov",subtitle:"The Transgressor",author:"Dostoevsky",work:"Crime and Punishment",color:"#8B3A3A",bg:"#150a0a",icon:"✦",
    summary:"You believe — perhaps rightly — that you are capable of more than the world allows. This creates dangerous pressure. You theorize your way into positions that feel liberating and are quietly devastating. Your suffering is real. So is your pride.",
    traits:[
      {label:"Behavioural Pattern",value:"You construct elaborate justifications for what you already want to do. The theory comes after the desire."},
      {label:"Core Fear",value:"Mediocrity. Being ordinary. Spending your capacities on things unworthy of them."},
      {label:"Hidden Strength",value:"Ferocious intellectual honesty — when you finally turn it on yourself."},
      {label:"Relationship Style",value:"Intense, asymmetric. You need people who can handle your full weight — and there are very few."},
      {label:"Shadow Self",value:"The 'extraordinary man' theory. You know it's flawed. You half-believe it anyway."},
    ],
    quote:"Pain and suffering are always inevitable for a large intelligence and a deep heart.",
    challenge:"Your intelligence is not a license. The question isn't whether you're capable — it's whether you can bear to be human.",
    tensions:["SISYPHUS","ALYOSHA"],affinities:["ZARATHUSTRA","UNDERGROUND_MAN"],
  },
  ALYOSHA: { id:"ALYOSHA",name:"Alyosha",subtitle:"The Luminous",author:"Dostoevsky",work:"The Brothers Karamazov",color:"#7a6a2a",bg:"#15120a",icon:"✶",
    summary:"You have seen the darkness and emerged not disillusioned but strangely more open. People confide in you. You don't fix their problems — you witness them. Your goodness is not naivety; it has been tested. That is what makes it real.",
    traits:[
      {label:"Behavioural Pattern",value:"Active, attending presence. You notice people. You remember what they told you three months ago."},
      {label:"Core Fear",value:"That love is not enough. That the darkness wins despite everything."},
      {label:"Hidden Strength",value:"You hold contradictions without needing to resolve them. Faith and doubt. Joy and grief."},
      {label:"Relationship Style",value:"People feel seen around you. This creates intimacy quickly — sometimes more than you intended."},
      {label:"Shadow Self",value:"Passive acceptance dressed as peace. Sometimes the loving thing is confrontation, not presence."},
    ],
    quote:"Love in action is a harsh and dreadful thing compared to love in dreams.",
    challenge:"Goodness is not the absence of conflict. Alyosha's love costs him. It costs you too — and that cost is the proof.",
    tensions:["ZARATHUSTRA","MEURSAULT"],affinities:["DEMIAN","SISYPHUS"],
  },
  UNDERGROUND_MAN: { id:"UNDERGROUND_MAN",name:"The Underground Man",subtitle:"The Hyper-Conscious",author:"Dostoevsky",work:"Notes from Underground",color:"#5A5A8B",bg:"#0c0c15",icon:"⬡",
    summary:"You see too clearly. Every social norm, comfortable lie, false cheerfulness — you see through it all. And the seeing paralyzes you. You know what people are doing and why. The knowledge doesn't help. It may be making things worse.",
    traits:[
      {label:"Behavioural Pattern",value:"Hyper-analysis that loops back on itself. You can argue any position — including against your own deepest desires."},
      {label:"Core Fear",value:"Being reduced to a formula. Being predicted. Being just another piano key in a rational system."},
      {label:"Hidden Strength",value:"Radical honesty — at least internally. You won't lie to yourself, even when lying would be more comfortable."},
      {label:"Relationship Style",value:"You oscillate between craving connection and pushing it away with compulsive spite."},
      {label:"Shadow Self",value:"Spite as philosophy. You sometimes act against your own interests just to prove you can."},
    ],
    quote:"I am a sick man. I am a spiteful man. I think my liver hurts.",
    challenge:"Awareness without action is its own cowardice. The Underground Man knows everything and does nothing. The exit is not more thinking.",
    tensions:["DIONYSUS","SISYPHUS"],affinities:["RASKOLNIKOV","ROQUENTIN"],
  },
  DEMIAN: { id:"DEMIAN",name:"Demian",subtitle:"The Seeker Between Worlds",author:"Hesse",work:"Demian / Steppenwolf",color:"#7a8a5a",bg:"#0e120a",icon:"◑",
    summary:"You have always sensed two worlds — the bright sanctioned one everyone pretends is the only one, and the darker, truer world beneath. You were drawn to the second not out of rebellion but necessity. You cannot unsee what you've seen.",
    traits:[
      {label:"Behavioural Pattern",value:"You seek people and ideas that crack things open. Safe conversations bore you physically."},
      {label:"Core Fear",value:"That the integration never comes. That you will always be between worlds, belonging fully to neither."},
      {label:"Hidden Strength",value:"You have done the interior work others avoid. You know your own darkness. That is rare."},
      {label:"Relationship Style",value:"You form deep bonds with people who can see what you see. You have few of them. They matter enormously."},
      {label:"Shadow Self",value:"The seeker as escape artist. Sometimes the journey inward is a way of not arriving anywhere."},
    ],
    quote:"I wanted only to try to live in accord with the promptings which came from my true self.",
    challenge:"The mark of Cain is not a curse — it is a calling. The question is what you build with it.",
    tensions:["UNDERGROUND_MAN","JOSEF_K"],affinities:["ALYOSHA","GREGOR"],
  },
  STEPPENWOLF: { id:"STEPPENWOLF",name:"Harry Haller",subtitle:"The Divided",author:"Hesse",work:"Steppenwolf",color:"#8a6a4a",bg:"#120e08",icon:"◐",
    summary:"You contain multitudes and they are at war. The bourgeois and the wolf. The intellectual and the animal. The person who wants comfort and the one who finds it suffocating. You are not broken — you are a person who hasn't yet learned to play all the instruments you possess.",
    traits:[
      {label:"Behavioural Pattern",value:"Alternating between intense engagement and complete withdrawal. Hot and cold, with little warm in between."},
      {label:"Core Fear",value:"That the wolf wins. Or worse — that the bourgeois wins. Either resolution feels like death."},
      {label:"Hidden Strength",value:"Your internal conflict means you cannot be complacent. You are always, uncomfortably, alive."},
      {label:"Relationship Style",value:"You fall hard for people who embody the part of yourself you're currently suppressing."},
      {label:"Shadow Self",value:"The romanticization of suffering. Pain as identity. The wolf as costume rather than truth."},
    ],
    quote:"He saw that all the hundred thousand pieces of life's game were in him, imprisoned in the dark.",
    challenge:"The Magic Theatre is not escape — it is education. You are not two wolves. You are a thousand things. Start naming them.",
    tensions:["MEURSAULT","SISYPHUS"],affinities:["DEMIAN","JOSEF_K"],
  },
  ROQUENTIN: { id:"ROQUENTIN",name:"Roquentin",subtitle:"The Nauseated",author:"Sartre",work:"Nausea",color:"#6a7a4a",bg:"#0c0f08",icon:"◬",
    summary:"You have looked at a chestnut tree root, a doorknob, your own hand — and suddenly the existence of things became unbearable. Not because they are terrible but because they simply ARE, without reason, without necessity, excessively, obscenely there.",
    traits:[
      {label:"Behavioural Pattern",value:"You notice what others filter out — the raw, unnarrated facticity of things. This makes you precise and occasionally overwhelmed."},
      {label:"Core Fear",value:"That existence is not just meaningless but actively excessive — a nausea without cure."},
      {label:"Hidden Strength",value:"You cannot lie to yourself about foundations. You see through every comfortable story. This is a terrifying gift."},
      {label:"Relationship Style",value:"You form connections then question their necessity. Why this person? Why now? The questioning is not cruelty — it is your nature."},
      {label:"Shadow Self",value:"The nausea as superiority. Looking down at the salauds from a height that is also a cage."},
    ],
    quote:"I exist. It's soft, so soft, so slow. And light: it seems as though it suspends in the air.",
    challenge:"Existence precedes essence — you are radically free to create meaning, not just observe its absence. The nausea is the beginning, not the conclusion.",
    tensions:["ALYOSHA","DIONYSUS"],affinities:["UNDERGROUND_MAN","GREGOR"],
  },
};

const QUESTIONS = [
  {id:1,scenario:"You are at a funeral. You did not know the person well, but others are weeping deeply. You feel nothing — or something so quiet it barely registers.",question:"What is the most honest thing you do with that?",
    choices:[
      {text:"Perform the grief anyway. The ritual matters more than whether the feeling is real.",weights:{GREGOR:3,JOSEF_K:2,STEPPENWOLF:1}},
      {text:"Stay still and present. You don't manufacture what isn't there.",weights:{MEURSAULT:4,SISYPHUS:1,ROQUENTIN:1}},
      {text:"Feel quietly ashamed. Something must be wrong with you.",weights:{UNDERGROUND_MAN:3,STEPPENWOLF:2,GREGOR:1}},
      {text:"Sit with it as a question — why don't I feel this? What does that mean about me?",weights:{ROQUENTIN:3,DEMIAN:3,UNDERGROUND_MAN:1}},
    ]},
  {id:2,scenario:"Someone you respect deeply tells you: 'I think you are capable of much more than you allow yourself.' They mean it kindly. You have heard it before.",question:"What is the feeling underneath your response?",
    choices:[
      {text:"A flare of recognition — and then something that closes quickly, like a door.",weights:{RASKOLNIKOV:3,ZARATHUSTRA:2,STEPPENWOLF:2}},
      {text:"Mild irritation. You are tired of being someone else's potential.",weights:{MEURSAULT:3,UNDERGROUND_MAN:2,GREGOR:1}},
      {text:"Genuine warmth — but also the awareness that they don't know what 'more' would cost.",weights:{DEMIAN:3,SISYPHUS:2,ALYOSHA:1}},
      {text:"The fear that they are right, and you have been choosing smallness deliberately.",weights:{GREGOR:3,JOSEF_K:2,STEPPENWOLF:2}},
    ]},
  {id:3,scenario:"You are three years into something — a relationship, a career, a city — that is not bad. Not painful. Simply not yours. Leaving would hurt people who have done nothing wrong.",question:"What do you do?",
    choices:[
      {text:"Stay. The hurt caused by leaving is real. The alternative is abstract.",weights:{GREGOR:3,ALYOSHA:2,JOSEF_K:1}},
      {text:"Leave. A life that is almost right is the most dangerous kind of wrong.",weights:{ZARATHUSTRA:3,DEMIAN:2,DIONYSUS:2}},
      {text:"Stay but begin, very quietly, to build the door.",weights:{SISYPHUS:3,STEPPENWOLF:2,ROQUENTIN:1}},
      {text:"Decide nothing — and watch yourself become someone who has decided.",weights:{UNDERGROUND_MAN:3,MEURSAULT:2,JOSEF_K:2}},
    ]},
  {id:4,scenario:"You have done something you are not proud of — nothing catastrophic, but real. Nobody knows. A year passes. You have not repeated it. It has not left you.",question:"What do you do with the fact that it hasn't left you?",
    choices:[
      {text:"Confess it — not because it will help them, but because you cannot keep carrying it alone.",weights:{RASKOLNIKOV:3,ALYOSHA:2,DEMIAN:1}},
      {text:"Let it be proof that you are still the kind of person who feels things. That is enough.",weights:{SISYPHUS:3,MEURSAULT:2,DIONYSUS:1}},
      {text:"Keep it. Repair what you can without disclosure. The confession would be for you, not them.",weights:{JOSEF_K:2,GREGOR:2,ROQUENTIN:2}},
      {text:"Examine it until you understand exactly why you did it — even if what you find is ugly.",weights:{UNDERGROUND_MAN:3,ROQUENTIN:3,RASKOLNIKOV:1}},
    ]},
  {id:5,scenario:"A child asks you: 'Do you think people are mostly good?' They are young enough that your answer will shape something in them.",question:"What do you actually say?",
    choices:[
      {text:"Yes — not because it's fully true, but because the belief itself makes it more true.",weights:{ALYOSHA:4,DEMIAN:1,SISYPHUS:1}},
      {text:"I think people are capable of both, and the difference is what they choose to practice.",weights:{ZARATHUSTRA:2,SISYPHUS:2,DIONYSUS:2}},
      {text:"I think people are mostly frightened — and frightened people do terrible things and beautiful ones.",weights:{STEPPENWOLF:3,UNDERGROUND_MAN:2,ALYOSHA:1}},
      {text:"I don't know. I think that's the right answer to hold.",weights:{MEURSAULT:3,ROQUENTIN:2,DEMIAN:2}},
    ]},
  {id:6,scenario:"At 3am, unable to sleep, you find yourself doing something you'd be embarrassed to admit in daylight — not shameful, just private. A ritual, an obsession, a thought you return to.",question:"What does that 3am self want that the daytime self won't admit?",
    choices:[
      {text:"To be seen — fully, without the performance of being fine.",weights:{RASKOLNIKOV:2,UNDERGROUND_MAN:2,STEPPENWOLF:2}},
      {text:"To stop. Just — for once — to not be the one holding everything together.",weights:{GREGOR:4,JOSEF_K:2,ALYOSHA:1}},
      {text:"To feel something that has no name and no use and doesn't need either.",weights:{DIONYSUS:3,DEMIAN:2,ROQUENTIN:2}},
      {text:"To know that all of this — all of it — was worth something.",weights:{SISYPHUS:3,ZARATHUSTRA:2,RASKOLNIKOV:1}},
    ]},
  {id:7,scenario:"You are given undeniable evidence that a belief you have held for years — about yourself, about how the world works — is wrong. Not partially wrong. Wrong.",question:"What breaks first?",
    choices:[
      {text:"The belief. You update, painfully but completely. You are not your opinions.",weights:{SISYPHUS:3,MEURSAULT:2,DIONYSUS:2}},
      {text:"Your trust in the person who showed you. You know they're right. You still resent them.",weights:{UNDERGROUND_MAN:3,RASKOLNIKOV:2,STEPPENWOLF:1}},
      {text:"Your sense of who you are. The belief was load-bearing. Now you don't know what's left.",weights:{DEMIAN:3,ROQUENTIN:3,GREGOR:1}},
      {text:"Nothing, immediately. You go quiet. You need weeks before you know what broke.",weights:{JOSEF_K:3,ALYOSHA:2,ZARATHUSTRA:1}},
    ]},
  {id:8,scenario:"You witness someone being publicly humiliated — not physically harmed, but genuinely degraded. You could intervene. It would cost you something real. Nobody would blame you for staying quiet.",question:"What determines whether you speak?",
    choices:[
      {text:"Whether you could live with yourself afterward. That is the only calculation.",weights:{ALYOSHA:3,ZARATHUSTRA:2,RASKOLNIKOV:1}},
      {text:"Whether intervening would actually help them — or just make you feel better.",weights:{MEURSAULT:2,SISYPHUS:3,ROQUENTIN:1}},
      {text:"Whether anyone else is going to. The collective silence is its own act.",weights:{DEMIAN:2,UNDERGROUND_MAN:2,JOSEF_K:2}},
      {text:"Honestly? Whether you are having a day when you have something left to give.",weights:{STEPPENWOLF:3,GREGOR:2,DIONYSUS:1}},
    ]},
  {id:9,scenario:"You are offered a version of your life with all the difficulty removed. Same people, same work — but the weight is gone. The grinding sense that things cost something. It would feel like relief.",question:"Do you take it?",
    choices:[
      {text:"No. The weight is how you know you're alive. Remove it and you remove something essential.",weights:{ZARATHUSTRA:3,DIONYSUS:2,RASKOLNIKOV:2}},
      {text:"You would want to say no. You would probably take it. This tells you something uncomfortable.",weights:{UNDERGROUND_MAN:3,STEPPENWOLF:2,GREGOR:2}},
      {text:"No — not nobly. Because you wouldn't trust it. The ease would feel like a trap.",weights:{JOSEF_K:3,ROQUENTIN:2,DEMIAN:1}},
      {text:"Yes, without guilt. Suffering is not a credential. Ease is not a betrayal.",weights:{MEURSAULT:3,SISYPHUS:2,ALYOSHA:1}},
    ]},
  {id:10,scenario:"At the end of your life — imagining it now, honestly — you are asked to name the thing you protected most carefully. Not what you built or achieved. What you protected.",question:"What is it?",
    choices:[
      {text:"The ability to see clearly. To not be fooled — not by others, not by yourself.",weights:{ROQUENTIN:3,UNDERGROUND_MAN:2,MEURSAULT:2}},
      {text:"The people. The ones you loved. Everything else was in service of that.",weights:{ALYOSHA:4,GREGOR:2,DEMIAN:1}},
      {text:"The part of you that refused. That never fully surrendered to what the world wanted you to become.",weights:{ZARATHUSTRA:3,DIONYSUS:2,RASKOLNIKOV:2}},
      {text:"The question itself. You stayed uncertain. You kept asking. That felt like the most honest thing.",weights:{SISYPHUS:3,STEPPENWOLF:2,DEMIAN:2}},
    ]},
];

const CLASHES = {
  "JOSEF_K-MEURSAULT":{title:"The Accused vs. The Stranger",description:"Part of you fights the system anxiously; part of you doesn't register it as real. Two responses to the same absurd world — and you contain both."},
  "ZARATHUSTRA-UNDERGROUND_MAN":{title:"The Overcomer vs. The Paralyzed",description:"You have the firepower of both — one pushes upward, the other spirals inward. On good days you are Zarathustra. On dark days, the Underground Man."},
  "RASKOLNIKOV-SISYPHUS":{title:"The Transgressor vs. The Revolter",description:"Both refuse the world as given — but one wants to stand above it, the other to engage it fully. Your tension is between transcendence and acceptance."},
  "ALYOSHA-MEURSAULT":{title:"The Luminous vs. The Stranger",description:"You may love deeply but cannot perform the rituals of love — or perform them without the feeling. The gap between inner and outer is where you live."},
  "DEMIAN-ROQUENTIN":{title:"The Seeker vs. The Nauseated",description:"Both have looked beneath the surface. Demian finds meaning in the darkness; Roquentin finds only excessive existence. You oscillate between them."},
  "STEPPENWOLF-DIONYSUS":{title:"The Divided vs. The Affirmer",description:"You contain contradictions — but are you at war with them or dancing with them? Somewhere between the suffering and the celebration."},
  "GREGOR-RASKOLNIKOV":{title:"The Transformed vs. The Transgressor",description:"One erases himself for others; one believes he transcends them. You carry both — the self-effacing servant and the secretly convinced exceptional."},
  "ALYOSHA-ZARATHUSTRA":{title:"The Luminous vs. The Overcomer",description:"Love versus will. You want to love people as they are and push them to become more. This is either wisdom or an impossible demand."},
};

const COMPAT_STATUS = {
  SOULMATE:    { label:"Soulmate",       symbol:"◈◈", color:"#c4882a", desc:"Rare recognition. You understand each other without explanation." },
  MIRROR:      { label:"Dark Mirror",    symbol:"◇◇", color:"#8a4a8a", desc:"You see yourself in them — the parts you haven't faced yet." },
  MAGNETIC:    { label:"Magnetic Clash", symbol:"⚡",  color:"#8B3A3A", desc:"Intense, combustible. You cannot ignore each other." },
  DIFFICULT:   { label:"Difficult Truth",symbol:"⬡",  color:"#5A5A8B", desc:"They show you what you avoid. It is uncomfortable. It is necessary." },
  INDIFFERENT: { label:"Ships at Night", symbol:"◇",  color:"#3a3a3a", desc:"You exist in parallel worlds. No animosity — just distance." },
};

const COMPATIBILITY = {
  JOSEF_K:{GREGOR:{score:88,note:"Two people who carry the world in silence. You recognize each other's exhaustion without a word. The danger: you enable each other's self-erasure."},ZARATHUSTRA:{score:22,note:"Zarathustra is everything Josef K. cannot be — unafraid, ascending, loud. K. finds him exhausting. Zarathustra finds K. tragic. Both are right."},DIONYSUS:{score:35,note:"The Dionysian's 'yes to everything' bewilders K., who can barely say yes to anything. Fascinating in small doses. Unsustainable as a bond."},MEURSAULT:{score:60,note:"Both live inside systems that don't fit. But K. fights anxiously; Meursault doesn't register the cage. They are the same problem approached from opposite directions."},SISYPHUS:{score:55,note:"Sisyphus has made peace with the boulder. K. is still arguing with it. There's respect here — and a gap. K. wonders if Sisyphus is wise or simply resigned."},RASKOLNIKOV:{score:42,note:"Raskolnikov wants to transcend the system K. is trapped in. Their conversations spiral. Neither can give the other what they need."},ALYOSHA:{score:70,note:"Alyosha doesn't fix K.'s problem. He just stays. For someone used to being processed by systems, being witnessed is disorienting and quietly healing."},UNDERGROUND_MAN:{score:78,note:"They understand each other's paralysis. Long silences, then sudden bursts of painful honesty. The risk: they can keep each other stuck."},DEMIAN:{score:50,note:"Demian sees a door where K. sees a wall. Intriguing, but K. suspects Demian's freedom is a story he tells himself."},STEPPENWOLF:{score:82,note:"Both are divided men trapped in forms that don't contain them. The bond is immediate and melancholy. They drink together and don't pretend."},ROQUENTIN:{score:65,note:"Two people who notice what others don't — the absurdity, the excess, the weight of existing. Their conversations are the most honest either of them has."}},
  GREGOR:{ZARATHUSTRA:{score:18,note:"Zarathustra demands becoming. Gregor has spent his life disappearing. The mismatch is almost cruel — though Zarathustra would say the cruelty is necessary."},DIONYSUS:{score:40,note:"The Dionysian's appetite for life is alien to Gregor, who has learned to want nothing. But occasionally, something in Gregor stirs. Briefly."},MEURSAULT:{score:45,note:"Meursault doesn't perform care, which is either alienating or a relief. Gregor can't quite tell. There's no obligation here — and that feels strange."},SISYPHUS:{score:72,note:"Both keep going. Sisyphus by choice; Gregor by habit. Sisyphus might be the one who finally asks Gregor: is this what you want? No one else thought to ask."},RASKOLNIKOV:{score:30,note:"Raskolnikov's hunger for greatness is incomprehensible to someone who has given everything away. There's pity here, and contempt, and something more complicated."},ALYOSHA:{score:90,note:"Alyosha loves without condition. For Gregor, who has only known conditional love, this is almost unbearable. He doesn't know what to do with it. He stays anyway."},UNDERGROUND_MAN:{score:55,note:"The Underground Man sees Gregor's trap clearly and says so, unkindly. It hurts. It's also the most honest thing anyone has said to him."},DEMIAN:{score:68,note:"Demian looks at Gregor and sees the transformation that hasn't happened yet — the one Gregor is terrified of. He doesn't turn away. That matters."},STEPPENWOLF:{score:60,note:"Both are living in forms that don't fit. Harry Haller recognizes the exhaustion. He won't romanticize it, which Gregor secretly appreciates."},ROQUENTIN:{score:75,note:"Roquentin sees the obscene facticity of Gregor's existence — the sheer excessive weight of it — without flinching. This is its own kind of witnessing."},JOSEF_K:{score:88,note:"Two people who carry the world in silence. You recognize each other's exhaustion without a word. The danger: you enable each other's self-erasure."}},
  ZARATHUSTRA:{DIONYSUS:{score:92,note:"The philosophical alliance. Dionysus provides the fire; Zarathustra gives it direction. Together they are either magnificent or unlivable. Often both."},MEURSAULT:{score:68,note:"Zarathustra admires Meursault's refusal to perform. But Meursault's passivity frustrates him. 'You see clearly,' Zarathustra wants to say. 'Now DO something.'"},SISYPHUS:{score:62,note:"Mutual respect between two people who have chosen their burden. They disagree on whether acceptance is victory. The argument is generative."},RASKOLNIKOV:{score:78,note:"Raskolnikov is what Zarathustra would look like if the philosophy broke him before it made him. Zarathustra sees the ruins of something that could have been great."},ALYOSHA:{score:38,note:"The deepest philosophical divide in the room. Alyosha's love is everything Zarathustra suspects is a comfortable illusion. They are kind to each other. They do not understand each other."},UNDERGROUND_MAN:{score:28,note:"The Underground Man is the Last Man Zarathustra fears becoming — paralyzed, spiteful, brilliant and going nowhere. This is not contempt. It is recognition of a near miss."},DEMIAN:{score:80,note:"Demian is Zarathustra's student who graduated early. The relationship is equal parts admiration and rivalry. Both are trying to live at the edge of what's possible."},STEPPENWOLF:{score:55,note:"Harry Haller has the will but not the direction. Zarathustra finds him interesting but unresolved. Haller finds Zarathustra's certainty both inspiring and suspect."},ROQUENTIN:{score:32,note:"Roquentin's nausea is the enemy of everything Zarathustra affirms. They occupy the same philosophical universe and reach opposite conclusions. Cold respect. No warmth."},GREGOR:{score:18,note:"Zarathustra demands becoming. Gregor has spent his life disappearing. The mismatch is almost cruel — though Zarathustra would say the cruelty is necessary."},JOSEF_K:{score:22,note:"Zarathustra is everything Josef K. cannot be — unafraid, ascending, loud. K. finds him exhausting. Zarathustra finds K. tragic. Both are right."}},
  DIONYSUS:{MEURSAULT:{score:75,note:"Two people who don't perform. Meursault's stillness intrigues the Dionysian; the Dionysian's aliveness wakes something in Meursault. The most unexpected friendship in the room."},SISYPHUS:{score:70,note:"Both say yes. But the Dionysian says yes ecstatically; Sisyphus says yes quietly. They complement. Sisyphus steadies the Dionysian; the Dionysian reminds Sisyphus of joy."},RASKOLNIKOV:{score:60,note:"Raskolnikov's intensity draws the Dionysian in. But Raskolnikov's suffering is not the Dionysian kind — it doesn't transform, it accumulates. The Dionysian grows tired."},ALYOSHA:{score:65,note:"Different kinds of love. Alyosha loves carefully; the Dionysian loves recklessly. They recognize something real in each other across a significant gap."},UNDERGROUND_MAN:{score:20,note:"The Underground Man is the anti-Dionysian. Every yes the Dionysian makes, the Underground Man finds a reason to doubt. The relationship is quietly exhausting for both."},DEMIAN:{score:85,note:"Demian has found his darkness and made it his. The Dionysian has done the same. They are two people who have integrated their shadow — and recognize it in each other."},STEPPENWOLF:{score:78,note:"Harry Haller needs to learn to dance. The Dionysian can teach him — not the steps, but the permission. The most transformative pairing for Steppenwolf."},ROQUENTIN:{score:25,note:"Roquentin's nausea and the Dionysian's affirmation are irreconcilable. Not enemies — just utterly alien to each other. Brief contact. Mutual bewilderment."},ZARATHUSTRA:{score:92,note:"The philosophical alliance. Dionysus provides the fire; Zarathustra gives it direction. Together they are either magnificent or unlivable. Often both."},GREGOR:{score:40,note:"The Dionysian's appetite for life is alien to Gregor, who has learned to want nothing. But occasionally, something in Gregor stirs. Briefly."},JOSEF_K:{score:35,note:"The Dionysian's 'yes to everything' bewilders K., who can barely say yes to anything. Fascinating in small doses. Unsustainable as a bond."}},
  MEURSAULT:{SISYPHUS:{score:88,note:"The closest thing to soulmates in this room. Both have looked at meaninglessness and refused to collapse. Meursault feels it; Sisyphus names it. They do not need to talk much."},RASKOLNIKOV:{score:35,note:"Raskolnikov's guilt is everything Meursault doesn't feel. The gap is too wide for real understanding — though Meursault would listen without judgment, which is more than most offer."},ALYOSHA:{score:42,note:"Alyosha wants to love Meursault into feeling more. Meursault will not perform the feeling. There is genuine mutual respect — and a wall neither can quite cross."},UNDERGROUND_MAN:{score:50,note:"Both see through social performance. But the Underground Man seethes; Meursault is simply present. The Underground Man finds this either enviable or infuriating depending on the day."},DEMIAN:{score:60,note:"Demian sees Meursault's detachment as a threshold, not a destination. Meursault doesn't know what Demian means. He finds him interesting. That's saying something."},STEPPENWOLF:{score:45,note:"Harry Haller's inner war bewilders Meursault, who has no such war. The gap is wide. But occasionally Harry finds Meursault's stillness more peaceful than anything in himself."},ROQUENTIN:{score:72,note:"Both notice the raw existence of things. Roquentin is nauseated by it; Meursault is simply there. Roquentin envies this — and suspects it might be its own kind of blindness."},ZARATHUSTRA:{score:68,note:"Zarathustra admires Meursault's refusal to perform. But Meursault's passivity frustrates him. 'You see clearly — now DO something,' Zarathustra wants to say."},DIONYSUS:{score:75,note:"Two people who don't perform. Meursault's stillness intrigues the Dionysian; the Dionysian's aliveness wakes something in Meursault. The most unexpected friendship."},GREGOR:{score:45,note:"Meursault doesn't perform care, which is either alienating or a relief to Gregor. Gregor can't quite tell. There's no obligation here — and that feels strange."},JOSEF_K:{score:60,note:"Both live inside systems that don't fit. But K. fights anxiously; Meursault doesn't register the cage. Same problem, opposite directions."}},
  SISYPHUS:{RASKOLNIKOV:{score:40,note:"Sisyphus has made peace with what Raskolnikov is still at war with. There's no contempt here — only the mild sadness of watching someone fight a battle they've already lost."},ALYOSHA:{score:82,note:"Both have chosen to keep going in the face of evidence that stopping would be easier. Alyosha's love and Sisyphus's revolt are different shapes of the same defiant yes."},UNDERGROUND_MAN:{score:32,note:"Sisyphus has the one thing the Underground Man lacks: the capacity to act despite knowing. The Underground Man finds this either admirable or incomprehensible. Usually the latter."},DEMIAN:{score:76,note:"Demian is still building his boulder. Sisyphus has been pushing his for years. There's wisdom to offer, if Demian is willing to receive it — and he usually is."},STEPPENWOLF:{score:48,note:"Steppenwolf romanticizes his suffering; Sisyphus has deprogrammed exactly that. The conversations are useful. Haller resists them. He comes back."},ROQUENTIN:{score:55,note:"Roquentin sees the nausea at the bottom of things. Sisyphus has been there and named it something else: the foundation for revolt. They are close to the same place."},MEURSAULT:{score:88,note:"The closest thing to soulmates in this room. Both have looked at meaninglessness and refused to collapse. Meursault feels it; Sisyphus names it. They do not need to talk much."},ZARATHUSTRA:{score:62,note:"Mutual respect between two who have chosen their burden. They disagree on whether acceptance is victory. The argument is generative."},DIONYSUS:{score:70,note:"Both say yes. But the Dionysian says yes ecstatically; Sisyphus says yes quietly. They complement each other."},GREGOR:{score:72,note:"Sisyphus might be the one who finally asks Gregor: is this what you want? No one else thought to ask."},JOSEF_K:{score:55,note:"Sisyphus has made peace with the boulder. K. is still arguing with it. There's respect and a gap. K. wonders if Sisyphus is wise or simply resigned."}},
  RASKOLNIKOV:{ALYOSHA:{score:55,note:"Alyosha is the person Raskolnikov would need to become to be saved. He knows this. He resists it. He keeps returning to Alyosha anyway, which says everything."},UNDERGROUND_MAN:{score:80,note:"Two brilliant men who turned their intelligence against themselves. They understand each other's self-destruction in granular detail. The relationship is addictive and dangerous."},DEMIAN:{score:68,note:"Demian has integrated what Raskolnikov is trying to weaponize. There's a cautionary recognition here — and something that might, over time, be mentorship."},STEPPENWOLF:{score:62,note:"Both carry a divided self. But Raskolnikov's division is moral; Steppenwolf's is existential. They can drink together without explaining themselves. That's rare."},ROQUENTIN:{score:58,note:"Roquentin sees Raskolnikov's guilt as a philosophical problem. Raskolnikov finds this cold. But Roquentin's clarity about the weight of existing is the most honest diagnosis he's received."},ZARATHUSTRA:{score:78,note:"Raskolnikov is what Zarathustra would look like if the philosophy broke him before it made him. Zarathustra sees the ruins of something great."},DIONYSUS:{score:60,note:"Raskolnikov's intensity draws the Dionysian in. But his suffering accumulates rather than transforms. The Dionysian grows tired."},MEURSAULT:{score:35,note:"Raskolnikov's guilt is everything Meursault doesn't feel. Too wide a gap — though Meursault would listen without judgment."},GREGOR:{score:30,note:"Raskolnikov's hunger for greatness is incomprehensible to someone who has given everything away. Pity, contempt, and something more complicated."},JOSEF_K:{score:42,note:"Raskolnikov wants to transcend the system K. is trapped in. Their conversations spiral. Neither can give the other what they need."},SISYPHUS:{score:40,note:"Sisyphus has made peace with what Raskolnikov is at war with. The mild sadness of watching someone fight a battle already lost."}},
  ALYOSHA:{UNDERGROUND_MAN:{score:45,note:"Alyosha loves the Underground Man without requiring him to be better. The Underground Man finds this unbearable. He keeps testing it. It keeps holding. He doesn't know what to do with that."},DEMIAN:{score:80,note:"Both are trying to integrate darkness and light — Alyosha through love, Demian through knowledge. They learn from each other without either fully converting the other."},STEPPENWOLF:{score:72,note:"Alyosha sees the person inside the war. He doesn't ask Harry to resolve it — just to be present to it. Haller finds this disarming. He was ready for a fight."},ROQUENTIN:{score:38,note:"Roquentin's nausea and Alyosha's love are at philosophical war. Yet Alyosha listens to the nausea without arguing. This confuses Roquentin more than opposition would."},ZARATHUSTRA:{score:38,note:"The deepest philosophical divide in the room. Alyosha's love is everything Zarathustra suspects is comfortable illusion. They are kind. They do not understand each other."},DIONYSUS:{score:65,note:"Different kinds of love. Alyosha loves carefully; the Dionysian loves recklessly. They recognize something real in each other across a significant gap."},MEURSAULT:{score:42,note:"Alyosha wants to love Meursault into feeling more. Meursault will not perform the feeling. Genuine respect — and a wall neither can quite cross."},GREGOR:{score:90,note:"Alyosha loves without condition. For Gregor, who has only known conditional love, this is almost unbearable. He doesn't know what to do with it. He stays anyway."},JOSEF_K:{score:70,note:"Alyosha doesn't fix K.'s problem. He just stays. For someone used to being processed by systems, being witnessed is disorienting and quietly healing."},SISYPHUS:{score:82,note:"Both have chosen to keep going against evidence. Alyosha's love and Sisyphus's revolt are different shapes of the same defiant yes."},RASKOLNIKOV:{score:55,note:"Alyosha is the person Raskolnikov would need to become to be saved. He knows this. He resists. He keeps returning anyway, which says everything."}},
  UNDERGROUND_MAN:{DEMIAN:{score:52,note:"Demian found his way through the dark; the Underground Man is still in it. Demian's integration irritates him — it looks too easy. He suspects it cost more than it shows."},STEPPENWOLF:{score:85,note:"The most honest mirror in the room. Both are hyper-conscious men at war with themselves. Their conversations go to places others won't follow. Dangerous. Necessary."},ROQUENTIN:{score:88,note:"Two people who see through everything and are paralyzed by the seeing. They will spend hours on a single sentence, following it down. Nobody else has the patience for this. They do."},ZARATHUSTRA:{score:28,note:"The Underground Man is the Last Man Zarathustra fears becoming. This is not contempt — it is recognition of a near miss. The relationship is a mirror neither fully wants."},DIONYSUS:{score:20,note:"The Underground Man finds a reason to doubt every yes the Dionysian makes. The relationship is quietly exhausting for both."},MEURSAULT:{score:50,note:"Both see through social performance. But the Underground Man seethes; Meursault is simply present. He finds this either enviable or infuriating depending on the day."},GREGOR:{score:55,note:"The Underground Man sees Gregor's trap clearly and says so, unkindly. It hurts. It's also the most honest thing anyone has said to him."},JOSEF_K:{score:78,note:"They understand each other's paralysis intimately. Long silences, then sudden bursts of painful honesty. The risk: they keep each other stuck."},SISYPHUS:{score:32,note:"Sisyphus has the one thing the Underground Man lacks: the capacity to act despite knowing. He finds this admirable or incomprehensible. Usually the latter."},RASKOLNIKOV:{score:80,note:"Two brilliant men who turned intelligence against themselves. They understand each other's self-destruction in granular detail. Addictive and dangerous."},ALYOSHA:{score:45,note:"Alyosha loves him without requiring him to be better. He finds this unbearable. He keeps testing it. It keeps holding. He doesn't know what to do with that."}},
  DEMIAN:{STEPPENWOLF:{score:82,note:"Demian has found what Steppenwolf is looking for. Not an answer — a method. He doesn't give it away. He makes Haller work for it, which is the only way it holds."},ROQUENTIN:{score:58,note:"Demian finds meaning in the abyss; Roquentin finds nausea. Close to the same territory, different conclusions. A generative tension if both are willing."},ZARATHUSTRA:{score:80,note:"Demian is Zarathustra's student who graduated early. Equal parts admiration and rivalry. Both trying to live at the edge of what's possible."},DIONYSUS:{score:85,note:"Two people who have integrated their shadow. They recognize it in each other immediately. The bond is deep and requires no explanation."},MEURSAULT:{score:60,note:"Demian sees Meursault's detachment as a threshold, not a destination. Meursault doesn't know what he means. He finds him interesting. That's saying something."},GREGOR:{score:68,note:"Demian looks at Gregor and sees the transformation that hasn't happened yet. He doesn't turn away. That matters enormously."},JOSEF_K:{score:50,note:"Demian sees a door where K. sees a wall. Intriguing, but K. suspects Demian's freedom is a story he tells himself."},SISYPHUS:{score:76,note:"Demian is still building his boulder. Sisyphus has been pushing his for years. There's wisdom to offer, if Demian is willing to receive it."},RASKOLNIKOV:{score:68,note:"Demian has integrated what Raskolnikov is trying to weaponize. A cautionary recognition — and something that might, over time, become mentorship."},ALYOSHA:{score:80,note:"Both integrating darkness and light — Alyosha through love, Demian through knowledge. They learn from each other without either fully converting the other."},UNDERGROUND_MAN:{score:52,note:"Demian found his way through the dark; the Underground Man is still in it. His integration irritates him — it looks too easy."}},
  STEPPENWOLF:{ROQUENTIN:{score:70,note:"Both are nauseated by their own existence in different ways. Roquentin by the raw facticity of things; Steppenwolf by his own multiplicity. They sit together in it without performing comfort."},ZARATHUSTRA:{score:55,note:"Harry has the will but not the direction. Zarathustra finds him interesting but unresolved. Haller finds Zarathustra's certainty both inspiring and suspect."},DIONYSUS:{score:78,note:"Harry Haller needs to learn to dance. The Dionysian can teach him — not the steps, but the permission. The most transformative pairing for Steppenwolf."},MEURSAULT:{score:45,note:"Harry's inner war bewilders Meursault, who has no such war. Occasionally Harry finds Meursault's stillness more peaceful than anything inside himself."},GREGOR:{score:60,note:"Both are living in forms that don't fit. Harry Haller recognizes the exhaustion. He won't romanticize it, which Gregor secretly appreciates."},JOSEF_K:{score:82,note:"Both are divided men trapped in forms that don't contain them. The bond is immediate and melancholy. They drink together and don't pretend."},SISYPHUS:{score:48,note:"Steppenwolf romanticizes his suffering; Sisyphus has deprogrammed exactly that. The conversations are useful. Haller resists them. He comes back."},RASKOLNIKOV:{score:62,note:"Both carry a divided self — Raskolnikov's moral, Steppenwolf's existential. They can be in a room without explaining themselves. That's rare."},ALYOSHA:{score:72,note:"Alyosha sees the person inside the war. He doesn't ask Harry to resolve it — just to be present to it. Haller finds this disarming. He was ready for a fight."},UNDERGROUND_MAN:{score:85,note:"The most honest mirror in the room. Both hyper-conscious men at war with themselves. Their conversations go to places others won't follow."},DEMIAN:{score:82,note:"Demian has found what Steppenwolf is looking for. Not an answer — a method. He makes Haller work for it, which is the only way it holds."}},
  ROQUENTIN:{ZARATHUSTRA:{score:32,note:"Roquentin's nausea and Zarathustra's affirmation are irreconcilable. Not enemies — just alien. Brief contact. Mutual bewilderment. Cold respect."},DIONYSUS:{score:25,note:"The Dionysian's affirmation is exactly what Roquentin cannot manage. They are irreconcilable — not hostile, just pointing in opposite directions."},MEURSAULT:{score:72,note:"Both notice the raw existence of things. Roquentin is nauseated; Meursault is simply there. Roquentin envies this — and suspects it might be its own blindness."},SISYPHUS:{score:55,note:"Roquentin sees the nausea at the bottom of things. Sisyphus has been there and named it something else. They are close to the same place with different maps."},RASKOLNIKOV:{score:58,note:"Roquentin sees Raskolnikov's guilt as a philosophical problem. Raskolnikov finds this cold. But Roquentin's clarity is the most honest diagnosis he's received."},ALYOSHA:{score:38,note:"Roquentin's nausea and Alyosha's love are at philosophical war. Yet Alyosha listens without arguing. This confuses Roquentin more than opposition would."},UNDERGROUND_MAN:{score:88,note:"Two people who see through everything and are paralyzed by it. They will spend hours on a single sentence following it down. Nobody else has the patience. They do."},DEMIAN:{score:58,note:"Demian finds meaning in the abyss; Roquentin finds nausea. Close to the same territory, different conclusions. A generative tension if both are willing."},STEPPENWOLF:{score:70,note:"Both nauseated by existence in different ways. They sit together in it without performing comfort. The bond is quiet and real."},GREGOR:{score:75,note:"Roquentin sees the obscene facticity of Gregor's existence without flinching. This is its own kind of witnessing."},JOSEF_K:{score:65,note:"Two people who notice what others don't — the absurdity, the excess, the weight of existing. Their conversations are the most honest either of them has."}},
};
